---
name: CI with Maven
on: # when to run 
  push:
    branches:
      - main
jobs:
  buildwith17:
    name: "maven"
    runs-on: ubuntu-24.04
    steps:
      - name: print github context
        run: echo "${{ toJson(github) }}"     



